// This is a seam-focused example.
// For a full application scaffold, see context/archetypes/multi-backend-service.md.
//
// rust-server.rs — Rust gRPC inference server implementing InferenceService.
// Uses tonic for gRPC, prost for Protocol Buffers, and a minimal hyper HTTP
// server for the /healthz sidecar endpoint.
//
// Cargo.toml dependencies:
//   tonic = "0.12"
//   prost = "0.13"
//   tokio = { version = "1", features = ["full"] }
//   http-body-util = "0.1"
//   hyper = { version = "1", features = ["full"] }
//   hyper-util = { version = "0.1", features = ["tokio"] }
//
// build.rs:
//   fn main() -> Result<(), Box<dyn std::error::Error>> {
//       tonic_build::compile_protos("service.proto")?;
//       Ok(())
//   }
//
// Requires protoc in the build environment:
//   apt-get install protobuf-compiler

use std::time::Instant;
use tonic::{transport::Server, Request, Response, Status};

// Generated by tonic_build from service.proto.
pub mod inference {
    tonic::include_proto!("inference.v1");
}

use inference::inference_service_server::{InferenceService, InferenceServiceServer};
use inference::{PredictRequest, PredictResponse};

#[derive(Default)]
pub struct InferenceImpl;

#[tonic::async_trait]
impl InferenceService for InferenceImpl {
    async fn predict(
        &self,
        request: Request<PredictRequest>,
    ) -> Result<Response<PredictResponse>, Status> {
        let start = Instant::now();
        let req = request.into_inner();

        let (label, confidence) = if req.features.is_empty() {
            // Empty features: return a sentinel response rather than panic.
            ("undefined".to_string(), 0.0_f32)
        } else {
            let mean: f32 = req.features.iter().sum::<f32>() / req.features.len() as f32;
            // Clamp confidence to [0.0, 1.0].
            let confidence = mean.clamp(0.0, 1.0);
            let label = if mean > 0.5 {
                "positive".to_string()
            } else {
                "low-confidence".to_string()
            };
            (label, confidence)
        };

        let duration_ns = start.elapsed().as_nanos() as i64;
        eprintln!(
            "predict model_id={} correlation_id={} features={} label={} confidence={:.4} duration_ns={}",
            req.model_id,
            req.correlation_id,
            req.features.len(),
            label,
            confidence,
            duration_ns,
        );

        Ok(Response::new(PredictResponse {
            label,
            confidence,
            duration_ns,
        }))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let grpc_port: u16 = std::env::var("GRPC_PORT")
        .unwrap_or_else(|_| "50051".to_string())
        .parse()?;
    let health_port: u16 = std::env::var("HEALTH_PORT")
        .unwrap_or_else(|_| "8082".to_string())
        .parse()?;

    // Spawn the HTTP /healthz sidecar on a separate port.
    // docker-compose healthchecks use curl against this port; no grpc_health_probe needed.
    tokio::spawn(async move {
        run_health_server(health_port).await;
    });

    let addr = format!("0.0.0.0:{grpc_port}").parse()?;
    eprintln!("InferenceService gRPC listening on {addr}");
    Server::builder()
        .add_service(InferenceServiceServer::new(InferenceImpl::default()))
        .serve(addr)
        .await?;
    Ok(())
}

// run_health_server exposes GET /healthz on the sidecar port.
// Returns {"status":"ok"} for all requests — the gRPC server is up if this process is up.
async fn run_health_server(port: u16) {
    use http_body_util::Full;
    use hyper::body::Bytes;
    use hyper::server::conn::http1;
    use hyper::service::service_fn;
    use hyper::{Request as HReq, Response as HResp};
    use hyper_util::rt::TokioIo;
    use std::net::SocketAddr;
    use tokio::net::TcpListener;

    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    let listener = TcpListener::bind(addr).await.expect("health server bind");
    eprintln!("HTTP /healthz listening on {addr}");

    loop {
        let (stream, _) = listener.accept().await.expect("health accept");
        let io = TokioIo::new(stream);
        tokio::spawn(async move {
            let _ = http1::Builder::new()
                .serve_connection(
                    io,
                    service_fn(|_req: HReq<hyper::body::Incoming>| async {
                        Ok::<_, hyper::Error>(
                            HResp::new(Full::new(Bytes::from("{\"status\":\"ok\"}\n"))),
                        )
                    }),
                )
                .await;
        });
    }
}
