// This is a seam-focused example.
// For a full application scaffold, see context/archetypes/multi-backend-service.md.
//
// rust-side.rs — Rust tonic gRPC server implementing KernelService.Transform.
// Also exposes a minimal HTTP /healthz endpoint on a sidecar port.
//
// Cargo.toml dependencies:
//   tonic = "0.12"
//   prost = "0.13"
//   tokio = { version = "1", features = ["full"] }
//   hyper = { version = "1", features = ["full"] }
//   http-body-util = "0.1"
//   hyper-util = { version = "0.1", features = ["tokio"] }
//
// build.rs:
//   fn main() -> Result<(), Box<dyn std::error::Error>> {
//       tonic_build::compile_protos("service.proto")?;
//       Ok(())
//   }
//
// Environment variables:
//   GRPC_PORT    gRPC listen port (default: 50051)
//   HEALTH_PORT  HTTP /healthz port (default: 8082)

use std::time::Instant;
use tonic::{transport::Server, Request, Response, Status};

// Generated by tonic_build from service.proto during `cargo build`.
pub mod kernel {
    tonic::include_proto!("kernel.v1");
}

use kernel::kernel_service_server::{KernelService, KernelServiceServer};
use kernel::{TransformRequest, TransformResponse};

#[derive(Default)]
pub struct KernelImpl;

#[tonic::async_trait]
impl KernelService for KernelImpl {
    async fn transform(
        &self,
        request: Request<TransformRequest>,
    ) -> Result<Response<TransformResponse>, Status> {
        let start = Instant::now();
        let req = request.into_inner();

        if req.values.is_empty() {
            return Err(Status::invalid_argument("values must not be empty"));
        }

        let result: Vec<f64> = match req.operation.as_str() {
            "normalize" => {
                // Subtract mean, divide by std dev.
                // If fewer than 2 values, return input unchanged (no meaningful std dev).
                if req.values.len() < 2 {
                    req.values.clone()
                } else {
                    let n = req.values.len() as f64;
                    let mean = req.values.iter().sum::<f64>() / n;
                    let variance = req.values.iter().map(|v| (v - mean).powi(2)).sum::<f64>() / n;
                    let std_dev = variance.sqrt();
                    if std_dev == 0.0 {
                        // All values are the same — return zeros.
                        vec![0.0; req.values.len()]
                    } else {
                        req.values.iter().map(|v| (v - mean) / std_dev).collect()
                    }
                }
            }
            "mean" => {
                // Compute mean; return as a single-element array.
                let mean = req.values.iter().sum::<f64>() / req.values.len() as f64;
                vec![mean]
            }
            _ => {
                // Unknown operation: return values unchanged.
                req.values.clone()
            }
        };

        let duration_ns = start.elapsed().as_nanos() as i64;
        eprintln!(
            "transform operation={} values={} result_len={} duration_ns={}",
            req.operation,
            req.values.len(),
            result.len(),
            duration_ns
        );

        Ok(Response::new(TransformResponse {
            result,
            method: req.operation,
            duration_ns,
        }))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let grpc_port: u16 = std::env::var("GRPC_PORT")
        .unwrap_or_else(|_| "50051".to_string())
        .parse()?;
    let health_port: u16 = std::env::var("HEALTH_PORT")
        .unwrap_or_else(|_| "8082".to_string())
        .parse()?;

    // Spawn the HTTP healthz sidecar on a separate port.
    // The gRPC server and the healthz server run concurrently via tokio::spawn.
    tokio::spawn(async move {
        run_health_server(health_port).await;
    });

    let addr = format!("0.0.0.0:{grpc_port}").parse()?;
    eprintln!("KernelService gRPC listening on {addr}");
    Server::builder()
        .add_service(KernelServiceServer::new(KernelImpl::default()))
        .serve(addr)
        .await?;
    Ok(())
}

// run_health_server exposes GET /healthz on the sidecar port.
// Used by docker compose healthchecks and Kubernetes liveness probes.
async fn run_health_server(port: u16) {
    use http_body_util::Full;
    use hyper::body::Bytes;
    use hyper::server::conn::http1;
    use hyper::service::service_fn;
    use hyper::{Request as HReq, Response as HResp};
    use hyper_util::rt::TokioIo;
    use std::net::SocketAddr;
    use tokio::net::TcpListener;

    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    let listener = TcpListener::bind(addr).await.expect("health server bind");
    eprintln!("HTTP healthz listening on {addr}");

    loop {
        let (stream, _) = listener.accept().await.expect("health accept");
        let io = TokioIo::new(stream);
        tokio::spawn(async move {
            let _ = http1::Builder::new()
                .serve_connection(
                    io,
                    service_fn(|_req: HReq<hyper::body::Incoming>| async {
                        Ok::<_, hyper::Error>(
                            HResp::new(Full::new(Bytes::from("{\"status\":\"ok\"}\n"))),
                        )
                    }),
                )
                .await;
        });
    }
}
