source "https://rubygems.org"

ruby "~> 3.3.0"

gem "hanami-router", "~> 2.2"
gem "hanami-controller", "~> 2.2"
gem "hanami-view", "~> 2.2"
gem "puma", "~> 6.4"
gem "rackup", "~> 2.1"
gem "sequel", "~> 5.80"
gem "sqlite3", "~> 2.4"
