// Seam example: Rust compute kernel — tonic gRPC server (KernelService.Transform)
// Seam 2 of 2: Rust ← Go via gRPC — receives Transform requests from Go workers
// Not a full application. See context/stacks/trio-elixir-go-rust.md.
//
// Proto reuse note: this server implements the SAME kernel.v1 KernelService proto
// as examples/canonical-multi-backend/duos/scala-rust-grpc/. The Rust kernel is
// reusable across different callers — Scala (Akka Streams) and Go both speak the
// same kernel.v1 contract. Only the caller changes; the Rust server is unchanged.
//
// Cargo.toml dependencies:
//   tonic = "0.12"
//   prost = "0.13"
//   tokio = { version = "1", features = ["full"] }
//   http-body-util = "0.1"
//   hyper = { version = "1", features = ["full"] }
//   hyper-util = { version = "0.1", features = ["tokio"] }
//
// build.rs:
//   fn main() -> Result<(), Box<dyn std::error::Error>> {
//       tonic_build::compile_protos("service.proto")?;
//       Ok(())
//   }
//
// [build-dependencies]
//   tonic-build = "0.12"
//
// Environment variables:
//   GRPC_PORT    gRPC listen port (default: 50051)
//   HEALTH_PORT  HTTP /healthz sidecar port (default: 8082)

use std::time::Instant;
use tonic::{transport::Server, Request, Response, Status};

// Generated by tonic_build from service.proto during `cargo build`.
// Package: kernel.v1 — the same proto used in duos/scala-rust-grpc/.
pub mod kernel {
    tonic::include_proto!("kernel.v1");
}

use kernel::kernel_service_server::{KernelService, KernelServiceServer};
use kernel::{TransformRequest, TransformResponse};

#[derive(Default)]
pub struct KernelImpl;

#[tonic::async_trait]
impl KernelService for KernelImpl {
    // Seam 2: Go calls this RPC via gRPC after receiving a task from Elixir via NATS.
    // The result is returned to Go, which then publishes a completion event back to Elixir.
    async fn transform(
        &self,
        request: Request<TransformRequest>,
    ) -> Result<Response<TransformResponse>, Status> {
        let start = Instant::now();
        let req = request.into_inner();

        if req.values.is_empty() {
            return Err(Status::invalid_argument("values must not be empty"));
        }

        let result: Vec<f64> = match req.operation.as_str() {
            "normalize" => {
                // Min-max normalization: scale values to [0.0, 1.0].
                // If min == max (all values identical), return all zeros.
                let min = req.values.iter().cloned().fold(f64::INFINITY, f64::min);
                let max = req.values.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
                let range = max - min;
                if range == 0.0 {
                    vec![0.0; req.values.len()]
                } else {
                    req.values.iter().map(|v| (v - min) / range).collect()
                }
            }
            "mean" => {
                // Compute mean; return as a single-element array.
                let mean = req.values.iter().sum::<f64>() / req.values.len() as f64;
                vec![mean]
            }
            _ => {
                // Unknown operation: return values unchanged.
                req.values.clone()
            }
        };

        let duration_ns = start.elapsed().as_nanos() as i64;
        eprintln!(
            "Transform called: operation={} input_len={} result_len={} duration_ns={}",
            req.operation,
            req.values.len(),
            result.len(),
            duration_ns
        );

        Ok(Response::new(TransformResponse {
            result,
            method: req.operation,
            duration_ns,
        }))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let grpc_port: u16 = std::env::var("GRPC_PORT")
        .unwrap_or_else(|_| "50051".to_string())
        .parse()?;
    let health_port: u16 = std::env::var("HEALTH_PORT")
        .unwrap_or_else(|_| "8082".to_string())
        .parse()?;

    // Spawn the HTTP healthz sidecar on a separate tokio task.
    // docker-compose health checks use `curl http://localhost:8082/healthz` instead
    // of grpc_health_probe, avoiding the need to install grpc_health_probe in the container.
    tokio::spawn(async move {
        run_health_server(health_port).await;
    });

    let addr = format!("0.0.0.0:{grpc_port}").parse()?;
    eprintln!("rust-kernel: KernelService gRPC listening on {addr}");
    Server::builder()
        .add_service(KernelServiceServer::new(KernelImpl::default()))
        .serve(addr)
        .await?;
    Ok(())
}

// run_health_server exposes GET /healthz on the sidecar port.
// Used by docker compose healthchecks and Kubernetes liveness probes.
async fn run_health_server(port: u16) {
    use http_body_util::Full;
    use hyper::body::Bytes;
    use hyper::server::conn::http1;
    use hyper::service::service_fn;
    use hyper::{Request as HReq, Response as HResp};
    use hyper_util::rt::TokioIo;
    use std::net::SocketAddr;
    use tokio::net::TcpListener;

    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    let listener = TcpListener::bind(addr).await.expect("health server bind");
    eprintln!("rust-kernel: HTTP healthz listening on {addr}");

    loop {
        let (stream, _) = listener.accept().await.expect("health accept");
        let io = TokioIo::new(stream);
        tokio::spawn(async move {
            let _ = http1::Builder::new()
                .serve_connection(
                    io,
                    service_fn(|_req: HReq<hyper::body::Incoming>| async {
                        Ok::<_, hyper::Error>(
                            HResp::new(Full::new(Bytes::from("{\"status\":\"ok\"}\n"))),
                        )
                    }),
                )
                .await;
        });
    }
}
