// This is a seam-focused example.
// For a full application scaffold, see context/archetypes/multi-backend-service.md.
//
// rust-server.rs — Rust gRPC server implementing ComputeService.
// Uses tonic for gRPC and prost for Protocol Buffers.
// Also exposes a minimal HTTP /healthz endpoint on a sidecar port.
//
// Cargo.toml dependencies:
//   tonic = "0.12"
//   prost = "0.13"
//   tokio = { version = "1", features = ["full"] }
//   hyper = { version = "1", features = ["full"] }
//   http-body-util = "0.1"
//   hyper-util = { version = "0.1", features = ["tokio"] }
//
// build.rs:
//   fn main() -> Result<(), Box<dyn std::error::Error>> {
//       tonic_build::compile_protos("service.proto")?;
//       Ok(())
//   }

use std::time::Instant;
use tonic::{transport::Server, Request, Response, Status};

// Generated by tonic_build from service.proto.
pub mod compute {
    tonic::include_proto!("compute.v1");
}

use compute::compute_service_server::{ComputeService, ComputeServiceServer};
use compute::{
    ComputeRequest, ComputeResponse, HealthCheckRequest, HealthCheckResponse, ServingStatus,
};

#[derive(Default)]
pub struct ComputeImpl;

#[tonic::async_trait]
impl ComputeService for ComputeImpl {
    async fn compute(
        &self,
        request: Request<ComputeRequest>,
    ) -> Result<Response<ComputeResponse>, Status> {
        let start = Instant::now();
        let req = request.into_inner();

        let result = match req.method.as_str() {
            "mean" => {
                if req.values.is_empty() {
                    0.0
                } else {
                    req.values.iter().sum::<f64>() / req.values.len() as f64
                }
            }
            "sum" => req.values.iter().sum::<f64>(),
            "max" => req
                .values
                .iter()
                .cloned()
                .fold(f64::NEG_INFINITY, f64::max),
            "min" => req.values.iter().cloned().fold(f64::INFINITY, f64::min),
            unknown => {
                return Err(Status::invalid_argument(format!(
                    "unknown method: {unknown}"
                )))
            }
        };

        let duration_ns = start.elapsed().as_nanos() as i64;
        eprintln!(
            "compute method={} values={} result={:.4} duration_ns={}",
            req.method,
            req.values.len(),
            result,
            duration_ns
        );

        Ok(Response::new(ComputeResponse {
            result,
            method: req.method,
            duration_ns,
        }))
    }

    async fn check(
        &self,
        _request: Request<HealthCheckRequest>,
    ) -> Result<Response<HealthCheckResponse>, Status> {
        Ok(Response::new(HealthCheckResponse {
            status: ServingStatus::Serving as i32,
        }))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let grpc_port: u16 = std::env::var("GRPC_PORT")
        .unwrap_or_else(|_| "50051".to_string())
        .parse()?;
    let health_port: u16 = std::env::var("HEALTH_PORT")
        .unwrap_or_else(|_| "8082".to_string())
        .parse()?;

    // Spawn the HTTP healthz sidecar on a separate port.
    tokio::spawn(async move {
        run_health_server(health_port).await;
    });

    let addr = format!("0.0.0.0:{grpc_port}").parse()?;
    eprintln!("ComputeService gRPC listening on {addr}");
    Server::builder()
        .add_service(ComputeServiceServer::new(ComputeImpl::default()))
        .serve(addr)
        .await?;
    Ok(())
}

// run_health_server exposes GET /healthz on the sidecar port.
// Used by docker compose healthchecks and Kubernetes liveness probes.
async fn run_health_server(port: u16) {
    use http_body_util::Full;
    use hyper::body::Bytes;
    use hyper::server::conn::http1;
    use hyper::service::service_fn;
    use hyper::{Request as HReq, Response as HResp};
    use hyper_util::rt::TokioIo;
    use std::net::SocketAddr;
    use tokio::net::TcpListener;

    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    let listener = TcpListener::bind(addr).await.expect("health server bind");
    eprintln!("HTTP healthz listening on {addr}");

    loop {
        let (stream, _) = listener.accept().await.expect("health accept");
        let io = TokioIo::new(stream);
        tokio::spawn(async move {
            let _ = http1::Builder::new()
                .serve_connection(
                    io,
                    service_fn(|_req: HReq<hyper::body::Incoming>| async {
                        Ok::<_, hyper::Error>(
                            HResp::new(Full::new(Bytes::from("{\"status\":\"ok\"}\n"))),
                        )
                    }),
                )
                .await;
        });
    }
}
